#!/usr/bin/env bash
set -euo pipefail

# Build optional ATS elevation relief from SCS elevation samples already
# extracted by truckermudgeon/maps. Does NOT modify Steam/ATS or routing data.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOLS_ROOT="${TRUCKNAV_MAP_TOOLS_ROOT:-$REPO_ROOT/.tools/map-data}"
PARSE_DIR="${TRUCKNAV_ATS_PARSE_DIR:-$REPO_ROOT/build/map-data/ats-parser}"
OUT_ROOT="${TRUCKNAV_ATS_TRUCKNAV_DIR:-$REPO_ROOT/build/map-data/ats-trucknav}"
TARGET_DIR="$REPO_ROOT/public/data/ats/map-data/tiles"
SOURCE_DIR="$OUT_ROOT/terrain/wgs84"
PROJECTED_DIR="$OUT_ROOT/terrain/projected"
TILE_DIR="$OUT_ROOT/map-data/tiles"
ELEVATION_JSON="$PARSE_DIR/usa-elevation.json"

if [[ ! -s "$ELEVATION_JSON" ]]; then
  echo "Missing ATS elevation samples: $ELEVATION_JSON" >&2
  echo "These are generated by: bash scripts/map-data/parse-ats.sh" >&2
  echo "Do not rerun the parser if your local map is already working unless you need to." >&2
  exit 2
fi
if [[ ! -f "$TOOLS_ROOT/env.sh" ]]; then
  echo "Map tools are not configured. Run bash scripts/map-data/setup-map-tools.sh" >&2
  exit 3
fi

# shellcheck disable=SC1090
source "$TOOLS_ROOT/env.sh"

GENERATOR="$TRUCKNAV_MAPS_DIR/node_modules/.bin/generator"
TSX="$TRUCKNAV_MAPS_DIR/node_modules/.bin/tsx"
TIPPECANOE="$TOOLS_ROOT/tippecanoe/bin/tippecanoe"
if [[ ! -x "$GENERATOR" || ! -x "$TSX" ]]; then
  echo "Generator not ready. Run bash scripts/map-data/setup-map-tools.sh" >&2
  exit 4
fi
if [[ ! -x "$TIPPECANOE" ]]; then
  bash "$REPO_ROOT/scripts/map-data/setup-tippecanoe.sh"
fi
if [[ ! -f "$TARGET_DIR/roads.mp3" ]]; then
  echo "ATS map tiles not installed at: $TARGET_DIR" >&2
  echo "Build the normal ATS map first; terrain alone cannot replace it." >&2
  exit 5
fi

mkdir -p "$SOURCE_DIR" "$PROJECTED_DIR" "$TILE_DIR"
echo "=== Generating ATS elevation polygons (this can take time) ==="
echo "Source: $ELEVATION_JSON"
(
  cd "$TRUCKNAV_MAPS_DIR"
  NODE_OPTIONS="--max-old-space-size=12288" "$GENERATOR" contours \
    -m usa -i "$PARSE_DIR" -o "$SOURCE_DIR" -t geojson
)

SOURCE="$SOURCE_DIR/ats-contours.geojson"
PROJECTED="$PROJECTED_DIR/ats-contours.geojson"
if [[ ! -s "$SOURCE" ]]; then
  echo "Contour generation did not produce: $SOURCE" >&2
  exit 6
fi

echo
echo "=== Reprojecting ATS elevation polygons to TruckNav game coordinates ==="
REPROJECT_DST="$TRUCKNAV_MAPS_DIR/packages/clis/generator/trucknav-reproject-geojson.ts"
cp "$REPO_ROOT/scripts/map-data/trucknav-reproject-geojson.ts" "$REPROJECT_DST"
(
  cd "$TRUCKNAV_MAPS_DIR"
  NODE_OPTIONS="--max-old-space-size=12288" "$TSX" \
    "$REPROJECT_DST" usa "$SOURCE" "$PROJECTED"
)

echo
echo "=== Packaging elevation PMTiles ==="
OUTPUT="$TILE_DIR/terrain.mp3"
"$TIPPECANOE" -Z4 -z9 -B4 -b10 -aL -D8 --force \
  -l contours -y elevation -o "$OUTPUT" "$PROJECTED"

if [[ "$(head -c 7 "$OUTPUT")" != "PMTiles" ]]; then
  echo "Invalid elevation tiles header: $OUTPUT" >&2
  exit 7
fi

# Replace runtime terrain only after the new archive passes basic validation.
# Avoid changing routes, sprites or map-manifest files.
TEMP="$(mktemp "$TARGET_DIR/.terrain.mp3.XXXXXXXX")"
trap 'rm -f "$TEMP"' EXIT
cp "$OUTPUT" "$TEMP"
mv -f "$TEMP" "$TARGET_DIR/terrain.mp3"
trap - EXIT

echo "ATS elevation relief ready: $TARGET_DIR/terrain.mp3"
echo "Restart or reload TruckNav and select Terrain in the map legend."
